version: 0.0
os: linux
files:
  - source: /  # Path in your repository
    destination: /home/ec2-user/app  # Destination path on the instance

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root
